export const SEARCH_NOTE_START = 'SEARCH_NOTE_START';
export const SEARCH_NOTE_SUCCESS = 'SEARCH_NOTE_SUCCESS';
export const SEARCH_NOTE_FAILURE = 'SEARCH_NOTE_FAILURE';
export const SAVE_NOTE = 'SAVE_NOTE'